2020-08-08 15:57:40,828 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:43]
2020-08-10 08:19:27,613 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:43]
2020-08-10 08:19:33,908 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:43]
2020-08-10 08:45:02,809 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:43]
2020-08-10 08:45:39,176 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:43]
2020-08-10 08:46:22,930 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:43]
2020-08-10 08:53:39,842 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:43]
2020-08-10 09:21:15,248 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:43]
2020-08-10 10:06:16,568 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:45]
2020-08-10 10:06:46,186 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:45]
2020-08-10 10:39:36,556 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:46]
2020-08-10 10:39:40,542 ERROR: Exception on /login [GET] [in /opt/anaconda3/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/blayneb/Desktop/bjb_blog/app/routes.py", line 46, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/blayneb/Desktop/bjb_blog/app/templates/base.html", line 63, in template
    {% block app_content %}{% endblock %}
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/blayneb/Desktop/bjb_blog/app/templates/login.html", line 11, in root
    <span style="color: red;">[{{ error }}]</span>
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/blayneb/Desktop/bjb_blog/app/templates/base.html", line 63, in template
    {% block app_content %}{% endblock %}
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 543, in _generate
    optimized=self.optimized)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/compiler.py", line 82, in generate
    generator.visit(node)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/compiler.py", line 718, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'app_content' defined twice
2020-08-10 10:40:40,367 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:46]
2020-08-10 10:40:46,835 ERROR: Exception on /login [GET] [in /opt/anaconda3/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/blayneb/Desktop/bjb_blog/app/routes.py", line 46, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/blayneb/Desktop/bjb_blog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/blayneb/Desktop/bjb_blog/app/templates/login.html", line 14, in root
    <p>
  File "/Users/blayneb/Desktop/bjb_blog/app/templates/base.html", line 14, in root
    <span class="icon-bar"></span>
  File "/opt/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/opt/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/opt/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/opt/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 90, in block_body
  File "/Users/blayneb/Desktop/bjb_blog/app/templates/base.html", line 43, in block_navbar
    <li><a href="{{ url_for('main.user', username=current_user.username) }}">{{ _('Profile') }}</a></li>
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/opt/anaconda3/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'index' instead?
2020-08-10 10:42:48,786 INFO: Microblog startup [in /Users/blayneb/Desktop/bjb_blog/app/__init__.py:46]
